In [2]:
import numpy as np

In [3]:
scaler_one = np.array(3)

In [4]:
scaler_one

array(3)

In [5]:
vector_two = np.array([1, 2, 3])
vector_two

array([1, 2, 3])

In [6]:
print(vector_two.size)
print(vector_two.shape)
print(vector_two.dtype)

3
(3,)
int64


In [18]:
values_propagator = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
dm_container = values_propagator.shape

In [21]:
print(dm_container[2])

3


In [26]:
np.ones((4,3), dtype='int32')


np.int32(1)

In [27]:
np.random.randn(4,3)

array([[ 2.0785096 , -1.1152909 , -1.12246076],
       [-0.07310603, -0.48826943,  0.29729499],
       [-1.45474979,  1.84755794,  1.42540304],
       [ 0.15243219,  0.00881921,  1.02970055]])

In [32]:
np.random.random_sample(values_propagator.shape)

array([[[0.49807097, 0.75667354, 0.65501953],
        [0.93174618, 0.95892753, 0.96503416],
        [0.8614945 , 0.96822433, 0.61493683]],

       [[0.49985021, 0.30223545, 0.78344791],
        [0.31097582, 0.38668244, 0.26041365],
        [0.43956256, 0.28688451, 0.23465506]]])

In [34]:
#random integer
np.random.randint(1, 9, size=(2,2))

array([[4, 3],
       [8, 1]])

In [35]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])